// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: internal/jobs.proto

package internalpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// JobState enumerates the lifecycle states of a job tracked by a jobs.Store.
type JobState int32

const (
	JobState_JOB_STATE_UNSPECIFIED JobState = 0
	// JOB_STATE_PENDING: enqueued and due at or after available_at, not currently leased.
	JobState_JOB_STATE_PENDING JobState = 1
	// JOB_STATE_LEASED: handed out by Lease to a worker, awaiting Ack/Nack before lease_expires_at.
	JobState_JOB_STATE_LEASED JobState = 2
	// JOB_STATE_WAITING: a fan-out parent waiting on its outstanding children to complete.
	JobState_JOB_STATE_WAITING JobState = 3
	// JOB_STATE_SUCCEEDED: terminal, acknowledged by its handler.
	JobState_JOB_STATE_SUCCEEDED JobState = 4
	// JOB_STATE_DEAD_LETTER: terminal, retries exhausted or explicitly dead-lettered.
	JobState_JOB_STATE_DEAD_LETTER JobState = 5
)

// Enum value maps for JobState.
var (
	JobState_name = map[int32]string{
		0: "JOB_STATE_UNSPECIFIED",
		1: "JOB_STATE_PENDING",
		2: "JOB_STATE_LEASED",
		3: "JOB_STATE_WAITING",
		4: "JOB_STATE_SUCCEEDED",
		5: "JOB_STATE_DEAD_LETTER",
	}
	JobState_value = map[string]int32{
		"JOB_STATE_UNSPECIFIED": 0,
		"JOB_STATE_PENDING":     1,
		"JOB_STATE_LEASED":      2,
		"JOB_STATE_WAITING":     3,
		"JOB_STATE_SUCCEEDED":   4,
		"JOB_STATE_DEAD_LETTER": 5,
	}
)

func (x JobState) Enum() *JobState {
	p := new(JobState)
	*p = x
	return p
}

func (x JobState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobState) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_jobs_proto_enumTypes[0].Descriptor()
}

func (JobState) Type() protoreflect.EnumType {
	return &file_internal_jobs_proto_enumTypes[0]
}

func (x JobState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobState.Descriptor instead.
func (JobState) EnumDescriptor() ([]byte, []int) {
	return file_internal_jobs_proto_rawDescGZIP(), []int{0}
}

// BackoffKind selects the retry backoff curve applied after a Nack.
type BackoffKind int32

const (
	BackoffKind_BACKOFF_KIND_UNSPECIFIED BackoffKind = 0
	BackoffKind_BACKOFF_KIND_FIXED       BackoffKind = 1
	BackoffKind_BACKOFF_KIND_LINEAR      BackoffKind = 2
	BackoffKind_BACKOFF_KIND_EXPONENTIAL BackoffKind = 3
)

// Enum value maps for BackoffKind.
var (
	BackoffKind_name = map[int32]string{
		0: "BACKOFF_KIND_UNSPECIFIED",
		1: "BACKOFF_KIND_FIXED",
		2: "BACKOFF_KIND_LINEAR",
		3: "BACKOFF_KIND_EXPONENTIAL",
	}
	BackoffKind_value = map[string]int32{
		"BACKOFF_KIND_UNSPECIFIED": 0,
		"BACKOFF_KIND_FIXED":       1,
		"BACKOFF_KIND_LINEAR":      2,
		"BACKOFF_KIND_EXPONENTIAL": 3,
	}
)

func (x BackoffKind) Enum() *BackoffKind {
	p := new(BackoffKind)
	*p = x
	return p
}

func (x BackoffKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BackoffKind) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_jobs_proto_enumTypes[1].Descriptor()
}

func (BackoffKind) Type() protoreflect.EnumType {
	return &file_internal_jobs_proto_enumTypes[1]
}

func (x BackoffKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BackoffKind.Descriptor instead.
func (BackoffKind) EnumDescriptor() ([]byte, []int) {
	return file_internal_jobs_proto_rawDescGZIP(), []int{1}
}

// RetryPolicy configures how many times a job may be attempted and how long it
// waits between attempts after a Nack.
type RetryPolicy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Kind  BackoffKind            `protobuf:"varint,1,opt,name=kind,proto3,enum=internalpb.BackoffKind" json:"kind,omitempty"`
	// base is the fixed delay (BACKOFF_KIND_FIXED), the per-attempt increment
	// (BACKOFF_KIND_LINEAR), or the initial delay that doubles each attempt
	// (BACKOFF_KIND_EXPONENTIAL).
	Base *durationpb.Duration `protobuf:"bytes,2,opt,name=base,proto3" json:"base,omitempty"`
	// max_delay caps the computed delay. Zero means uncapped.
	MaxDelay *durationpb.Duration `protobuf:"bytes,3,opt,name=max_delay,json=maxDelay,proto3" json:"max_delay,omitempty"`
	// max_attempts is the total number of delivery attempts (including the
	// first) before the job is moved to the dead-letter state. Zero is
	// rejected by jobs.NewJob; there is no "unlimited" sentinel.
	MaxAttempts   int32 `protobuf:"varint,4,opt,name=max_attempts,json=maxAttempts,proto3" json:"max_attempts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryPolicy) Reset() {
	*x = RetryPolicy{}
	mi := &file_internal_jobs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryPolicy) ProtoMessage() {}

func (x *RetryPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_internal_jobs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryPolicy.ProtoReflect.Descriptor instead.
func (*RetryPolicy) Descriptor() ([]byte, []int) {
	return file_internal_jobs_proto_rawDescGZIP(), []int{0}
}

func (x *RetryPolicy) GetKind() BackoffKind {
	if x != nil {
		return x.Kind
	}
	return BackoffKind_BACKOFF_KIND_UNSPECIFIED
}

func (x *RetryPolicy) GetBase() *durationpb.Duration {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *RetryPolicy) GetMaxDelay() *durationpb.Duration {
	if x != nil {
		return x.MaxDelay
	}
	return nil
}

func (x *RetryPolicy) GetMaxAttempts() int32 {
	if x != nil {
		return x.MaxAttempts
	}
	return 0
}

// JobEnvelope is the durable, storage-agnostic representation of a job. It
// mirrors jobs.Job field-for-field and is the wire format a Store persists and
// the format fan-out children are addressed with across the cluster.
type JobEnvelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Queue string                 `protobuf:"bytes,2,opt,name=queue,proto3" json:"queue,omitempty"`
	// target_name is resolved via ActorSystem.ActorOf at delivery time, so the
	// job reaches whichever PID currently answers to that name regardless of
	// which node created it.
	TargetName string `protobuf:"bytes,3,opt,name=target_name,json=targetName,proto3" json:"target_name,omitempty"`
	// payload is the application message, encoded through the existing remoting
	// serialization pipeline (remote.ProtoSerializer): self-describing, embeds
	// the fully-qualified proto type name.
	Payload        []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	RetryPolicy    *RetryPolicy           `protobuf:"bytes,5,opt,name=retry_policy,json=retryPolicy,proto3" json:"retry_policy,omitempty"`
	Attempts       int32                  `protobuf:"varint,6,opt,name=attempts,proto3" json:"attempts,omitempty"`
	State          JobState               `protobuf:"varint,7,opt,name=state,proto3,enum=internalpb.JobState" json:"state,omitempty"`
	AvailableAt    *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=available_at,json=availableAt,proto3" json:"available_at,omitempty"`
	LeaseExpiresAt *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=lease_expires_at,json=leaseExpiresAt,proto3" json:"lease_expires_at,omitempty"`
	LeaseOwner     string                 `protobuf:"bytes,10,opt,name=lease_owner,json=leaseOwner,proto3" json:"lease_owner,omitempty"`
	LastError      string                 `protobuf:"bytes,11,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Fan-out/fan-in linkage. child_count is set only on a fan-out parent;
	// parent_id and child_index are set only on a fan-out child.
	ParentId      string `protobuf:"bytes,14,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	ChildIndex    int32  `protobuf:"varint,15,opt,name=child_index,json=childIndex,proto3" json:"child_index,omitempty"`
	ChildCount    int32  `protobuf:"varint,16,opt,name=child_count,json=childCount,proto3" json:"child_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobEnvelope) Reset() {
	*x = JobEnvelope{}
	mi := &file_internal_jobs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobEnvelope) ProtoMessage() {}

func (x *JobEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_internal_jobs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobEnvelope.ProtoReflect.Descriptor instead.
func (*JobEnvelope) Descriptor() ([]byte, []int) {
	return file_internal_jobs_proto_rawDescGZIP(), []int{1}
}

func (x *JobEnvelope) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *JobEnvelope) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *JobEnvelope) GetTargetName() string {
	if x != nil {
		return x.TargetName
	}
	return ""
}

func (x *JobEnvelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *JobEnvelope) GetRetryPolicy() *RetryPolicy {
	if x != nil {
		return x.RetryPolicy
	}
	return nil
}

func (x *JobEnvelope) GetAttempts() int32 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

func (x *JobEnvelope) GetState() JobState {
	if x != nil {
		return x.State
	}
	return JobState_JOB_STATE_UNSPECIFIED
}

func (x *JobEnvelope) GetAvailableAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AvailableAt
	}
	return nil
}

func (x *JobEnvelope) GetLeaseExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LeaseExpiresAt
	}
	return nil
}

func (x *JobEnvelope) GetLeaseOwner() string {
	if x != nil {
		return x.LeaseOwner
	}
	return ""
}

func (x *JobEnvelope) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *JobEnvelope) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *JobEnvelope) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *JobEnvelope) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *JobEnvelope) GetChildIndex() int32 {
	if x != nil {
		return x.ChildIndex
	}
	return 0
}

func (x *JobEnvelope) GetChildCount() int32 {
	if x != nil {
		return x.ChildCount
	}
	return 0
}

// JobResult is the outcome a fan-out child reports back to its parent when it
// finishes (successfully or not), used by a Store's CompleteChild to build the
// aggregated reduce-step delivery for the parent.
type JobResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChildIndex    int32                  `protobuf:"varint,1,opt,name=child_index,json=childIndex,proto3" json:"child_index,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Failed        bool                   `protobuf:"varint,3,opt,name=failed,proto3" json:"failed,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobResult) Reset() {
	*x = JobResult{}
	mi := &file_internal_jobs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobResult) ProtoMessage() {}

func (x *JobResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_jobs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobResult.ProtoReflect.Descriptor instead.
func (*JobResult) Descriptor() ([]byte, []int) {
	return file_internal_jobs_proto_rawDescGZIP(), []int{2}
}

func (x *JobResult) GetChildIndex() int32 {
	if x != nil {
		return x.ChildIndex
	}
	return 0
}

func (x *JobResult) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *JobResult) GetFailed() bool {
	if x != nil {
		return x.Failed
	}
	return false
}

func (x *JobResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// FanInEnvelope is the message delivered to a fan-out parent's target once all
// of its children have completed: the aggregated results, ordered by
// child_index.
type FanInEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Results       []*JobResult           `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FanInEnvelope) Reset() {
	*x = FanInEnvelope{}
	mi := &file_internal_jobs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FanInEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FanInEnvelope) ProtoMessage() {}

func (x *FanInEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_internal_jobs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FanInEnvelope.ProtoReflect.Descriptor instead.
func (*FanInEnvelope) Descriptor() ([]byte, []int) {
	return file_internal_jobs_proto_rawDescGZIP(), []int{3}
}

func (x *FanInEnvelope) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *FanInEnvelope) GetResults() []*JobResult {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_internal_jobs_proto protoreflect.FileDescriptor

const file_internal_jobs_proto_rawDesc = "" +
	"\n" +
	"\x13internal/jobs.proto\x12\n" +
	"internalpb\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc4\x01\n" +
	"\vRetryPolicy\x12+\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x17.internalpb.BackoffKindR\x04kind\x12-\n" +
	"\x04base\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x04base\x126\n" +
	"\tmax_delay\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\bmaxDelay\x12!\n" +
	"\fmax_attempts\x18\x04 \x01(\x05R\vmaxAttempts\"\x8c\x05\n" +
	"\vJobEnvelope\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05queue\x18\x02 \x01(\tR\x05queue\x12\x1f\n" +
	"\vtarget_name\x18\x03 \x01(\tR\n" +
	"targetName\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x12:\n" +
	"\fretry_policy\x18\x05 \x01(\v2\x17.internalpb.RetryPolicyR\vretryPolicy\x12\x1a\n" +
	"\battempts\x18\x06 \x01(\x05R\battempts\x12*\n" +
	"\x05state\x18\a \x01(\x0e2\x14.internalpb.JobStateR\x05state\x12=\n" +
	"\favailable_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\vavailableAt\x12D\n" +
	"\x10lease_expires_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\x0eleaseExpiresAt\x12\x1f\n" +
	"\vlease_owner\x18\n" +
	" \x01(\tR\n" +
	"leaseOwner\x12\x1d\n" +
	"\n" +
	"last_error\x18\v \x01(\tR\tlastError\x129\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1b\n" +
	"\tparent_id\x18\x0e \x01(\tR\bparentId\x12\x1f\n" +
	"\vchild_index\x18\x0f \x01(\x05R\n" +
	"childIndex\x12\x1f\n" +
	"\vchild_count\x18\x10 \x01(\x05R\n" +
	"childCount\"t\n" +
	"\tJobResult\x12\x1f\n" +
	"\vchild_index\x18\x01 \x01(\x05R\n" +
	"childIndex\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x16\n" +
	"\x06failed\x18\x03 \x01(\bR\x06failed\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"W\n" +
	"\rFanInEnvelope\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12/\n" +
	"\aresults\x18\x02 \x03(\v2\x15.internalpb.JobResultR\aresults*\x9d\x01\n" +
	"\bJobState\x12\x19\n" +
	"\x15JOB_STATE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11JOB_STATE_PENDING\x10\x01\x12\x14\n" +
	"\x10JOB_STATE_LEASED\x10\x02\x12\x15\n" +
	"\x11JOB_STATE_WAITING\x10\x03\x12\x17\n" +
	"\x13JOB_STATE_SUCCEEDED\x10\x04\x12\x19\n" +
	"\x15JOB_STATE_DEAD_LETTER\x10\x05*z\n" +
	"\vBackoffKind\x12\x1c\n" +
	"\x18BACKOFF_KIND_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12BACKOFF_KIND_FIXED\x10\x01\x12\x17\n" +
	"\x13BACKOFF_KIND_LINEAR\x10\x02\x12\x1c\n" +
	"\x18BACKOFF_KIND_EXPONENTIAL\x10\x03B\xa2\x01\n" +
	"\x0ecom.internalpbB\tJobsProtoH\x02P\x01Z;github.com/tochemey/goakt/v4/internal/internalpb;internalpb\xa2\x02\x03IXX\xaa\x02\n" +
	"Internalpb\xca\x02\n" +
	"Internalpb\xe2\x02\x16Internalpb\\GPBMetadata\xea\x02\n" +
	"Internalpbb\x06proto3"

var (
	file_internal_jobs_proto_rawDescOnce sync.Once
	file_internal_jobs_proto_rawDescData []byte
)

func file_internal_jobs_proto_rawDescGZIP() []byte {
	file_internal_jobs_proto_rawDescOnce.Do(func() {
		file_internal_jobs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_jobs_proto_rawDesc), len(file_internal_jobs_proto_rawDesc)))
	})
	return file_internal_jobs_proto_rawDescData
}

var file_internal_jobs_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_internal_jobs_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_jobs_proto_goTypes = []any{
	(JobState)(0),                 // 0: internalpb.JobState
	(BackoffKind)(0),              // 1: internalpb.BackoffKind
	(*RetryPolicy)(nil),           // 2: internalpb.RetryPolicy
	(*JobEnvelope)(nil),           // 3: internalpb.JobEnvelope
	(*JobResult)(nil),             // 4: internalpb.JobResult
	(*FanInEnvelope)(nil),         // 5: internalpb.FanInEnvelope
	(*durationpb.Duration)(nil),   // 6: google.protobuf.Duration
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_internal_jobs_proto_depIdxs = []int32{
	1,  // 0: internalpb.RetryPolicy.kind:type_name -> internalpb.BackoffKind
	6,  // 1: internalpb.RetryPolicy.base:type_name -> google.protobuf.Duration
	6,  // 2: internalpb.RetryPolicy.max_delay:type_name -> google.protobuf.Duration
	2,  // 3: internalpb.JobEnvelope.retry_policy:type_name -> internalpb.RetryPolicy
	0,  // 4: internalpb.JobEnvelope.state:type_name -> internalpb.JobState
	7,  // 5: internalpb.JobEnvelope.available_at:type_name -> google.protobuf.Timestamp
	7,  // 6: internalpb.JobEnvelope.lease_expires_at:type_name -> google.protobuf.Timestamp
	7,  // 7: internalpb.JobEnvelope.created_at:type_name -> google.protobuf.Timestamp
	7,  // 8: internalpb.JobEnvelope.updated_at:type_name -> google.protobuf.Timestamp
	4,  // 9: internalpb.FanInEnvelope.results:type_name -> internalpb.JobResult
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_internal_jobs_proto_init() }
func file_internal_jobs_proto_init() {
	if File_internal_jobs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_jobs_proto_rawDesc), len(file_internal_jobs_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_jobs_proto_goTypes,
		DependencyIndexes: file_internal_jobs_proto_depIdxs,
		EnumInfos:         file_internal_jobs_proto_enumTypes,
		MessageInfos:      file_internal_jobs_proto_msgTypes,
	}.Build()
	File_internal_jobs_proto = out.File
	file_internal_jobs_proto_goTypes = nil
	file_internal_jobs_proto_depIdxs = nil
}
