// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: internal/scheduler.proto

package internalpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ScheduledMessage is the durable delivery intent persisted for a scheduled
// message when the actor system's scheduler is configured with a persistent
// go-quartz JobQueue (see actor.WithSchedulerJobQueue). Scheduled job closures
// cannot be serialized, so instead of persisting the closure the scheduler
// persists this envelope: enough information to resolve the target actor and
// re-deliver the payload after a process restart.
type ScheduledMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Specifies the schedule reference used to cancel, pause, or resume the
	// schedule via the ActorSystem scheduling API.
	Reference string `protobuf:"bytes,1,opt,name=reference,proto3" json:"reference,omitempty"`
	// Specifies the name of the actor the message is delivered to. The target
	// is resolved by name at fire time via ActorSystem.ActorOf, so delivery
	// works regardless of which process instance currently owns that name.
	TargetName string `protobuf:"bytes,2,opt,name=target_name,json=targetName,proto3" json:"target_name,omitempty"`
	// Specifies the name of the sender actor to resolve at fire time. Left
	// empty when the schedule was created without an explicit sender, in which
	// case the message is delivered from ActorSystem.NoSender().
	SenderName string `protobuf:"bytes,3,opt,name=sender_name,json=senderName,proto3" json:"sender_name,omitempty"`
	// Specifies the message payload, encoded through the existing remoting
	// serialization pipeline (remote.ProtoSerializer). The encoding is
	// self-describing: it embeds the fully-qualified proto type name so the
	// payload can be decoded back into its concrete type without additional
	// out-of-band coordination.
	Payload []byte `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	// Specifies when the message fires.
	Trigger *ScheduleTrigger `protobuf:"bytes,5,opt,name=trigger,proto3" json:"trigger,omitempty"`
	// Specifies whether delivery of each trigger tick must be arbitrated
	// cluster-wide so exactly one node fires (see actor.WithClusterSingleFire).
	// Carried in the envelope so the semantics survive a process restart when
	// the schedule is rebuilt from a persistent JobQueue.
	ClusterSingleFire bool `protobuf:"varint,6,opt,name=cluster_single_fire,json=clusterSingleFire,proto3" json:"cluster_single_fire,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ScheduledMessage) Reset() {
	*x = ScheduledMessage{}
	mi := &file_internal_scheduler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduledMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduledMessage) ProtoMessage() {}

func (x *ScheduledMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_scheduler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduledMessage.ProtoReflect.Descriptor instead.
func (*ScheduledMessage) Descriptor() ([]byte, []int) {
	return file_internal_scheduler_proto_rawDescGZIP(), []int{0}
}

func (x *ScheduledMessage) GetReference() string {
	if x != nil {
		return x.Reference
	}
	return ""
}

func (x *ScheduledMessage) GetTargetName() string {
	if x != nil {
		return x.TargetName
	}
	return ""
}

func (x *ScheduledMessage) GetSenderName() string {
	if x != nil {
		return x.SenderName
	}
	return ""
}

func (x *ScheduledMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ScheduledMessage) GetTrigger() *ScheduleTrigger {
	if x != nil {
		return x.Trigger
	}
	return nil
}

func (x *ScheduledMessage) GetClusterSingleFire() bool {
	if x != nil {
		return x.ClusterSingleFire
	}
	return false
}

// ScheduleTrigger describes one of the three trigger kinds supported by the
// scheduler: a one-time delay, a fixed interval, or a cron expression.
type ScheduleTrigger struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*ScheduleTrigger_Once
	//	*ScheduleTrigger_Interval
	//	*ScheduleTrigger_Cron
	Kind          isScheduleTrigger_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleTrigger) Reset() {
	*x = ScheduleTrigger{}
	mi := &file_internal_scheduler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleTrigger) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleTrigger) ProtoMessage() {}

func (x *ScheduleTrigger) ProtoReflect() protoreflect.Message {
	mi := &file_internal_scheduler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleTrigger.ProtoReflect.Descriptor instead.
func (*ScheduleTrigger) Descriptor() ([]byte, []int) {
	return file_internal_scheduler_proto_rawDescGZIP(), []int{1}
}

func (x *ScheduleTrigger) GetKind() isScheduleTrigger_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *ScheduleTrigger) GetOnce() *OnceTrigger {
	if x != nil {
		if x, ok := x.Kind.(*ScheduleTrigger_Once); ok {
			return x.Once
		}
	}
	return nil
}

func (x *ScheduleTrigger) GetInterval() *IntervalTrigger {
	if x != nil {
		if x, ok := x.Kind.(*ScheduleTrigger_Interval); ok {
			return x.Interval
		}
	}
	return nil
}

func (x *ScheduleTrigger) GetCron() *CronTrigger {
	if x != nil {
		if x, ok := x.Kind.(*ScheduleTrigger_Cron); ok {
			return x.Cron
		}
	}
	return nil
}

type isScheduleTrigger_Kind interface {
	isScheduleTrigger_Kind()
}

type ScheduleTrigger_Once struct {
	Once *OnceTrigger `protobuf:"bytes,1,opt,name=once,proto3,oneof"`
}

type ScheduleTrigger_Interval struct {
	Interval *IntervalTrigger `protobuf:"bytes,2,opt,name=interval,proto3,oneof"`
}

type ScheduleTrigger_Cron struct {
	Cron *CronTrigger `protobuf:"bytes,3,opt,name=cron,proto3,oneof"`
}

func (*ScheduleTrigger_Once) isScheduleTrigger_Kind() {}

func (*ScheduleTrigger_Interval) isScheduleTrigger_Kind() {}

func (*ScheduleTrigger_Cron) isScheduleTrigger_Kind() {}

// OnceTrigger fires exactly one time after delay has elapsed.
type OnceTrigger struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Specifies the delay before the message fires.
	Delay         *durationpb.Duration `protobuf:"bytes,1,opt,name=delay,proto3" json:"delay,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnceTrigger) Reset() {
	*x = OnceTrigger{}
	mi := &file_internal_scheduler_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnceTrigger) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnceTrigger) ProtoMessage() {}

func (x *OnceTrigger) ProtoReflect() protoreflect.Message {
	mi := &file_internal_scheduler_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnceTrigger.ProtoReflect.Descriptor instead.
func (*OnceTrigger) Descriptor() ([]byte, []int) {
	return file_internal_scheduler_proto_rawDescGZIP(), []int{2}
}

func (x *OnceTrigger) GetDelay() *durationpb.Duration {
	if x != nil {
		return x.Delay
	}
	return nil
}

// IntervalTrigger fires repeatedly, waiting interval between deliveries.
type IntervalTrigger struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Specifies the fixed delay between deliveries.
	Interval      *durationpb.Duration `protobuf:"bytes,1,opt,name=interval,proto3" json:"interval,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntervalTrigger) Reset() {
	*x = IntervalTrigger{}
	mi := &file_internal_scheduler_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntervalTrigger) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntervalTrigger) ProtoMessage() {}

func (x *IntervalTrigger) ProtoReflect() protoreflect.Message {
	mi := &file_internal_scheduler_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntervalTrigger.ProtoReflect.Descriptor instead.
func (*IntervalTrigger) Descriptor() ([]byte, []int) {
	return file_internal_scheduler_proto_rawDescGZIP(), []int{3}
}

func (x *IntervalTrigger) GetInterval() *durationpb.Duration {
	if x != nil {
		return x.Interval
	}
	return nil
}

// CronTrigger fires according to a cron expression evaluated in timezone.
type CronTrigger struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Specifies the cron expression, e.g. "0 */5 * * * *".
	Expression string `protobuf:"bytes,1,opt,name=expression,proto3" json:"expression,omitempty"`
	// Specifies the IANA timezone name the expression is evaluated in, e.g.
	// "America/New_York". Empty means UTC.
	Timezone      string `protobuf:"bytes,2,opt,name=timezone,proto3" json:"timezone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CronTrigger) Reset() {
	*x = CronTrigger{}
	mi := &file_internal_scheduler_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CronTrigger) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CronTrigger) ProtoMessage() {}

func (x *CronTrigger) ProtoReflect() protoreflect.Message {
	mi := &file_internal_scheduler_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CronTrigger.ProtoReflect.Descriptor instead.
func (*CronTrigger) Descriptor() ([]byte, []int) {
	return file_internal_scheduler_proto_rawDescGZIP(), []int{4}
}

func (x *CronTrigger) GetExpression() string {
	if x != nil {
		return x.Expression
	}
	return ""
}

func (x *CronTrigger) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

var File_internal_scheduler_proto protoreflect.FileDescriptor

const file_internal_scheduler_proto_rawDesc = "" +
	"\n" +
	"\x18internal/scheduler.proto\x12\n" +
	"internalpb\x1a\x1egoogle/protobuf/duration.proto\"\xf3\x01\n" +
	"\x10ScheduledMessage\x12\x1c\n" +
	"\treference\x18\x01 \x01(\tR\treference\x12\x1f\n" +
	"\vtarget_name\x18\x02 \x01(\tR\n" +
	"targetName\x12\x1f\n" +
	"\vsender_name\x18\x03 \x01(\tR\n" +
	"senderName\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x125\n" +
	"\atrigger\x18\x05 \x01(\v2\x1b.internalpb.ScheduleTriggerR\atrigger\x12.\n" +
	"\x13cluster_single_fire\x18\x06 \x01(\bR\x11clusterSingleFire\"\xb2\x01\n" +
	"\x0fScheduleTrigger\x12-\n" +
	"\x04once\x18\x01 \x01(\v2\x17.internalpb.OnceTriggerH\x00R\x04once\x129\n" +
	"\binterval\x18\x02 \x01(\v2\x1b.internalpb.IntervalTriggerH\x00R\binterval\x12-\n" +
	"\x04cron\x18\x03 \x01(\v2\x17.internalpb.CronTriggerH\x00R\x04cronB\x06\n" +
	"\x04kind\">\n" +
	"\vOnceTrigger\x12/\n" +
	"\x05delay\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\x05delay\"H\n" +
	"\x0fIntervalTrigger\x125\n" +
	"\binterval\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\binterval\"I\n" +
	"\vCronTrigger\x12\x1e\n" +
	"\n" +
	"expression\x18\x01 \x01(\tR\n" +
	"expression\x12\x1a\n" +
	"\btimezone\x18\x02 \x01(\tR\btimezoneB\xa7\x01\n" +
	"\x0ecom.internalpbB\x0eSchedulerProtoH\x02P\x01Z;github.com/tochemey/goakt/v4/internal/internalpb;internalpb\xa2\x02\x03IXX\xaa\x02\n" +
	"Internalpb\xca\x02\n" +
	"Internalpb\xe2\x02\x16Internalpb\\GPBMetadata\xea\x02\n" +
	"Internalpbb\x06proto3"

var (
	file_internal_scheduler_proto_rawDescOnce sync.Once
	file_internal_scheduler_proto_rawDescData []byte
)

func file_internal_scheduler_proto_rawDescGZIP() []byte {
	file_internal_scheduler_proto_rawDescOnce.Do(func() {
		file_internal_scheduler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_scheduler_proto_rawDesc), len(file_internal_scheduler_proto_rawDesc)))
	})
	return file_internal_scheduler_proto_rawDescData
}

var file_internal_scheduler_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_internal_scheduler_proto_goTypes = []any{
	(*ScheduledMessage)(nil),    // 0: internalpb.ScheduledMessage
	(*ScheduleTrigger)(nil),     // 1: internalpb.ScheduleTrigger
	(*OnceTrigger)(nil),         // 2: internalpb.OnceTrigger
	(*IntervalTrigger)(nil),     // 3: internalpb.IntervalTrigger
	(*CronTrigger)(nil),         // 4: internalpb.CronTrigger
	(*durationpb.Duration)(nil), // 5: google.protobuf.Duration
}
var file_internal_scheduler_proto_depIdxs = []int32{
	1, // 0: internalpb.ScheduledMessage.trigger:type_name -> internalpb.ScheduleTrigger
	2, // 1: internalpb.ScheduleTrigger.once:type_name -> internalpb.OnceTrigger
	3, // 2: internalpb.ScheduleTrigger.interval:type_name -> internalpb.IntervalTrigger
	4, // 3: internalpb.ScheduleTrigger.cron:type_name -> internalpb.CronTrigger
	5, // 4: internalpb.OnceTrigger.delay:type_name -> google.protobuf.Duration
	5, // 5: internalpb.IntervalTrigger.interval:type_name -> google.protobuf.Duration
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_internal_scheduler_proto_init() }
func file_internal_scheduler_proto_init() {
	if File_internal_scheduler_proto != nil {
		return
	}
	file_internal_scheduler_proto_msgTypes[1].OneofWrappers = []any{
		(*ScheduleTrigger_Once)(nil),
		(*ScheduleTrigger_Interval)(nil),
		(*ScheduleTrigger_Cron)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_scheduler_proto_rawDesc), len(file_internal_scheduler_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_scheduler_proto_goTypes,
		DependencyIndexes: file_internal_scheduler_proto_depIdxs,
		MessageInfos:      file_internal_scheduler_proto_msgTypes,
	}.Build()
	File_internal_scheduler_proto = out.File
	file_internal_scheduler_proto_goTypes = nil
	file_internal_scheduler_proto_depIdxs = nil
}
